"""資料收集模組共用欄位定義。"""

from __future__ import annotations

OHLCV_COLUMNS = [
    "timestamp",
    "symbol",
    "exchange",
    "interval",
    "open",
    "high",
    "low",
    "close",
    "volume",
    "quote_asset_volume",
    "number_of_trades",
    "taker_buy_base_volume",
    "taker_buy_quote_volume",
    "open_time_ms",
    "close_time_ms",
    "collected_at",
]

EQUITY_OHLCV_COLUMNS = [
    "timestamp",
    "symbol",
    "exchange",
    "interval",
    "open",
    "high",
    "low",
    "close",
    "adj_close",
    "volume",
    "dividends",
    "stock_splits",
    "collected_at",
]

REQUIRED_OHLCV_COLUMNS = [
    "timestamp",
    "open",
    "high",
    "low",
    "close",
    "volume",
]

MARKET_DATA_COLUMNS = [
    "timestamp",
    "symbol",
    "exchange",
    "price_change",
    "price_change_percent",
    "weighted_avg_price",
    "prev_close_price",
    "last_price",
    "last_qty",
    "bid_price",
    "bid_qty",
    "ask_price",
    "ask_qty",
    "open_price",
    "high_price",
    "low_price",
    "volume",
    "quote_volume",
    "open_time_ms",
    "close_time_ms",
    "first_trade_id",
    "last_trade_id",
    "trade_count",
    "collected_at",
]

REQUIRED_MARKET_DATA_COLUMNS = [
    "timestamp",
    "symbol",
    "price_change",
    "price_change_percent",
    "volume",
    "quote_volume",
    "trade_count",
]

DERIVATIVES_CONTEXT_COLUMNS = [
    "timestamp",
    "symbol",
    "exchange",
    "interval",
    "funding_rate",
    "mark_price",
    "open_interest",
    "open_interest_value",
    "open_interest_change",
    "bid_price",
    "ask_price",
    "spread_bps",
    "global_long_short_ratio",
    "global_long_account",
    "global_short_account",
    "taker_buy_sell_ratio",
    "taker_buy_volume",
    "taker_sell_volume",
    "basis_rate",
    "basis_price",
    "index_price",
    "collected_at",
]

ORDER_BOOK_CONTEXT_COLUMNS = [
    "timestamp",
    "symbol",
    "exchange",
    "last_update_id",
    "best_bid",
    "best_ask",
    "midpoint",
    "spread_bps",
    "microprice",
    "microprice_deviation_bps",
    "bid_depth_5",
    "ask_depth_5",
    "imbalance_5",
    "bid_depth_10",
    "ask_depth_10",
    "imbalance_10",
    "bid_depth_20",
    "ask_depth_20",
    "imbalance_20",
    "collected_at",
]
